### PR TITLE
Upgrade plugin to Flutter 2 and Null-safety

### PR DESCRIPTION
**Pull request by galunecandrey**

### CODE REVIEW

**Comment by eis6aer** [comment]
Is this going to be merged soon?

**Comment by nporter-adbe** [comment]
@eis6aer Yeah we're hoping to merge this and get the other plugins updated soon with Flutter 2 & Null-safety.

**Comment by eis6aer** [comment]
Thanks @nporter-adbe !!

**Review by eis6aer — APPROVED** [review]
LGTM, it would be a good thing to migrate this to Kotlin in the future or is there any specific reason not to do so?

**Comment by nporter-adbe** [comment]
@eis6aer Is there any benefit to migrating to Kotlin?

**Comment by eis6aer** [comment]
> @eis6aer Is there any benefit to migrating to Kotlin?

Just to be in the trend @nporter-adbe I can work on that after null safety release if that's ok with you

**Review by nporter-adbe — APPROVED** [review]
Thanks for this! Will get this published shortly.

**Comment by nporter-adbe** [comment]
@eis6aer @galunecandrey We also need some null-safety here, if you have time to contribute that'd be awesome!
 https://github.com/adobe/flutter_assurance

**Pull request merged**
